### ISSUE TITLE
Provide means to sort `Cw` `CreateWindow::value_list` to avoid panic

### ISSUE THREAD

**Issue by wez** [rust-x-bindings/rust-xcb#189]
I was surprised by:

```
thread 'main' panicked at 'CreateWindow::value_list must be sorted!'
```

If ordering is required (I'm not sure if that is true?), then there should be some way to see what the correct order should be from the documentation, or, more ergonomically, `Cw` should implement `Ord` and allow the data to be sorted in code.

As it stands, the source of this crate has to be examined to find the private method that is used to check for this condition to determine what that ordering should be.

**Comment by rtbo** [comment]
This requirement comes from XCB directly that specifies that `value_list` must be sorted in the order of the `Cw` enum.
I don't sort in `CreateWindow` to avoid runtime penalty.
I will add proper documentation for this.
The `value_list` is generally defined at compile time, so it is best to define in the right order rather than to sort it at run-time.

**Comment by wez** [comment]
Makes sense.  I think it would be good to define `Ord` for situations where the value list might be created dynamically though!

**Comment by rtbo** [comment]
#207 implements `Ord` for `Cw` and similar types.
Note it is still not enough for `x::CreateWindow` request where `value_list` must be sorted AND have distinct values (at most one of each `Cw` member)

**Comment by wez** [comment]
Thanks!
