### ISSUE TITLE
panic: Could not resolve randr Event with response_type 120 and first_event 89

### ISSUE THREAD

**Issue by dch** [rust-x-bindings/rust-xcb#204]
reporting this as discovered in wezterm project, crashes on startup, i.e.
at moment of trying to spawn a new window.

- Dell XPS13 from around 2017
- intel i915 gpu + kmod 5.10.113_6 (equivalent to Linux 5.10 DRM)
- FreeBSD 13.1-RELEASE-p2 amd64
- X11 + i3

```
thread 'main' panicked at 'internal error: entered unreachable code:
  Could not resolve randr Event with response_type 120 and first_event 89',
  /wrkdirs/usr/ports/x11/wezterm/work/target/x86_64-unknown-freebsd/release/build/xcb-ad01777c72ac85b1/out/randr.rs:777:18
```

https://github.com/wez/wezterm/issues/2559#issuecomment-1264340175 has following logs

[bt.txt](https://github.com/wez/wezterm/files/9690208/bt.txt)
[xorg.log](https://github.com/wez/wezterm/files/9690212/xorg.log)
[xrandr_properties.txt](https://github.com/wez/wezterm/files/9699442/xrandr_properties.txt)

**Comment by rtbo** [comment]
I tried to launch wezterm, and it seems to run without problem.
Please post the output of 
```
xdpyinfo -display :0 -queryExtensions | awk '/^number of extensions:/,/^default screen number/'
```

**Comment by rtbo** [comment]
@wez @dch I see what happens.
You are receiving DRI2 events from the X server which can happen on some driver configs when activating hardware acceleration even if you don't perform any DRI2 direct request. This is really related to Xlib and to specific GPU drivers.

To clarify a bit, the extensions you pass to `xcb::Connection::connect***` only affect rust-xcb event and error resolution, but will not affect which event you can receive from the server.

Because the extension was not activated when opening the connection, rust-xcb does not try to look-up this event and hit the unreachable code. You see a RandR related error because it is the extension activated with highest `base_event` lower than 120 (which is a bug on my side).

The PR #205 is normally fixing this bug, `Event::Unknown` is returned instead of a panic.

I'm not sure though that it is 100% OK to ignore the event though. @wez You should check my [opengl_window](https://github.com/rust-x-bindings/rust-xcb/blob/7e7fb4b3e4eb48196cc3734822cfc6eb7c01cbde/examples/opengl_window.rs#L290) example. There is some code handling DRI2 events and some references to email threads. On a previous computer I had, not handling the events resulted in rendering problems which I solved with the code in `rewire_event` that rewires those events back to `libgl`. (Since #205 you can forward forward directly `UnknownEvent` raw pointer, you don't need to activate DRI2 in rust-xcb).

**Comment by wez** [comment]
Hmmm, that makes sense. I pushed a commit that requests Dri2.
I already had the rewire_event stuff in the code:
https://github.com/wez/wezterm/blob/main/window/src/os/x11/connection.rs#L432-L445
Let's see if that resolves this!

**Comment by dch** [comment]
reporting here for completeness, thanks @rtbo and @wez its resolved!
