### ISSUE TITLE
More Documentation :-)

### ISSUE THREAD

**Issue by insipx** [rust-x-bindings/rust-xcb#36]
Hey, i've noticed for some items in this library the documentation can be a bit lacking. IE: InternAtom, InternAtomReply etc. The functions inside of those implicits should at least be documented (for example, I thought I had to use xcb_intern_atom_reply before I found that it is included in this library by checking the generate source code).

If you point me in the direction of adding this documentation in the XML file from which the Rust Code is generated, I would be happy to add it as I go through using the library. I would just need to know what format is needed in order to properly generate.

**Comment by rtbo** [comment]
As you noticed, the protocol documentation is generated from XML.
Generated HTML for rust-xcb is available here:
http://rtbo.github.io/rust-xcb/xcb/index.html

You won't find detailed documentation about specific `xcb_*_reply` function as replies API and C implementation are generated from requests.
With `rust-xcb`, you have to use the `xcb::intern_atom` request, that returns a cookie that has a `get_reply` method.
It turns out, `xcb::intern_atom` is documented here:
http://rtbo.github.io/rust-xcb/xcb/xproto/fn.intern_atom.html

Request/Reply/Event general mechanism is documented under the `xcb `crate root comment.

That being said, it is true that XCB _protocol_ documentation covers probably < 10% of the whole API.
I imported the XML protocol definition directly from the [xcb-proto](https://xcb.freedesktop.org/) source package (`v1.11.1` if I recall). 
This is where documentation effort of the XML definition should go. I believe XCB guys will warmly welcome such effort.

**Comment by rtbo** [comment]
The `v1.0` generated documentation is much better.

**Comment by rtbo** [comment]
[v1.0.0](https://crates.io/crates/xcb/1.0.0) is released.
