### ISSUE TITLE
Mismatch between modifiers type (u16) used in grab_key and ModMask (u32)

### ISSUE THREAD

**Issue by mgsloan** [rust-x-bindings/rust-xcb#44]
In [grab_key_checked](http://rtbo.github.io/rust-xcb/xcb/xproto/fn.grab_key_checked.html), the type of `modifiers` is `u16`, but the type of `MOD_MASK_CONTROL` is `ModMask` - http://rtbo.github.io/rust-xcb/xcb/xproto/type.ModMask.html - which is `u32`.

I realize this is the sort of thing one gets with auto generated wrappers, but it'd be great if these types matched!

Similarly, with the same function, http://rtbo.github.io/rust-xcb/xcb/xproto/constant.GRAB_MODE_ASYNC.html is `u32` whereas `pointer_mode` / `keyboard_mode` are `u8`.  I believe there's a theme here of the constants being `u32` whereas the usage sites being smaller

**Comment by rtbo** [comment]
What matters most is the function signature. This is done correctly today.
I think all enums are backed with `u32` type, which is similar to C (both enums and literal integers are 32 bits in C)
It just happens that Rust do not allow implicit casting, so you need to cast it yourself to fit the function signature.

However when I see this: [xproto.xml#L2784](https://github.com/rtbo/rust-xcb/blob/a485d4787fef76bd47e16b485b401ed7de85b7ae/xml/xproto.xml#L2784), I think it's possible to have the safe wrapper accept the correct type (ModMask aka u32), and cast internally to u16 for calling the FFI function (and of course without changing the FFI signature, which would break compatibility with X).

Your PR should do this instead of trying to change ModMask to u16, which will only be a guess in the end.

**Comment by mgsloan** [comment]
Ahh, yes, I think it would be ideal if functions took the correct flag type.  Would help a lot when trying to figure out what to pass to functions.

I'm coming from Haskell, still getting the ropes of rust.  I'd be inclined to use zero cost abstractions for this - https://aturon.github.io/features/types/newtype.html .  It seems that the `bitflags!` macro does this among other niceties - https://doc.rust-lang.org/bitflags/bitflags/index.html

> I think all enums are backed with u32 type, which is similar to C (both enums and literal integers are 32 bits in C)

Hmm, but is this necessary?  Thinking it'd be nice to use the smaller representation to avoid casting.  I think there is a good way to do this without casting - look at the usages of the enum type - and if they all consistently have the same representation - use that type.

Would you be likely to accept a PR that added `bitflags!` and tried to use the right sizes for the enums?

**Comment by rtbo** [comment]
You can do it step by step.
Give the requests as `grab_key` a `ModMask` that is casted into an `u16` in a transparent way (that is `grab_key_checked` takes a ModMask and pass a u16 to `ffi::xproto::xcb_grab_key_checked`) is a PR that I will definitely accept.
Regarding `bitflags!`, I have to evaluate what usage benefit it brings vs the code of an additional dependency.

**Comment by rtbo** [comment]
Fixed by `v1.0`.
See https://rust-x-bindings.github.io/rust-xcb/branches/v1.0-dev/xcb/x/struct.GrabKey.html
`GrabKey::modifiers` has type `ModMask` which is a safe `bitflags!` struct.

**Comment by rtbo** [comment]
[v1.0.0](https://crates.io/crates/xcb/1.0.0) is released.
