### ISSUE TITLE
Be more rust idiomatic

### ISSUE THREAD

**Issue by prasannavl** [rust-x-bindings/rust-xcb#59]
Many of the binding currently don't really do the idiomatic rust thing. I thought it might be a good idea to start gathering them here, and then hopefully change them if it can be agreed upon:

**Connection**
- `get_setup` currently panics when the pointer is null. Should return `Result` instead, and `Err` when that happens.
-  `flush` current returns a bool on failure. The rust way would be to do a `Result<()>`, with an `Err`. This way the clippy, or even the compiler itself can indicate a point of failure.

**Comment by psychon** [comment]
> get_setup currently panics when the pointer is null. Should return Result instead, and Err when that happens.

This should be (more or less) unreachable. The only way to get an `xcb_connection_t` with `xcb_get_setup(c) == NULL` is when `xcb_connect()` failed and returned a connection in an error state. Such a connection cannot easily be constructed correctly (`connect()` certainly cannot and if the error check is moved into `from_raw_conn()`, then I think it should be entirely impossible to get this).

<details><summary>Well, there is one other possibility...</summary>
One could also have a very old version of libxcb. Namely, before https://gitlab.freedesktop.org/xorg/lib/libxcb/commit/c4e40f646b8da4fd112ea54a612c880be5e942a8, `xcb_get_setup` started returning NULL when a connection entered an error state. This commit is part of libxcb 1.12 which was released in May 2016, so is not really "ancient old".
</details>

------

For `flush` failing: Well... I would argue that no one cares about that error. Especially since error states in libxcb are "sticky" and ones a connection had an error, it will always have it.

**Comment by rtbo** [comment]
[v1.0.0](https://crates.io/crates/xcb/1.0.0) is released.
